# Token configuré via la variable SONAR_TOKEN dans GitHub Secrets
sonar.projectKey=Projet-Wildlens

# Le nom et la version affichés dans l'interface SonarQube
sonar.projectName=Projet Wildlens
sonar.projectVersion=1.0

# Le chemin relatif aux fichiers que vous souhaitez analyser
sonar.sources=src

# Exclure certains répertoires, ici les dépendances de Composer (si utilisé)
sonar.exclusions=vendor/**

# Encodage du code source
sonar.sourceEncoding=UTF-8
