spring.application.name=wildlensApi
server.port=${PORT:8082}
spring.main.web-application-type=servlet
server.address=0.0.0.0

jwt.secret=${JWT_SECRET:localDevSecretPleaseChange}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/wildlens}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=${DB_SCHEMA:wildlens6}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.flyway.enabled=true
spring.flyway.create-schemas=true
spring.flyway.default-schema=${DB_SCHEMA:wildlens6}
spring.flyway.locations=classpath:db/migration

app.wildlens-prefix-url=${APP_URL:http://localhost:8082}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never